# Generated by Django 4.2.10 on 2024-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('curso', models.CharField(max_length=20)),
            ],
        ),
    ]
